Repository RocketChat/rocketchat.github.io, pull requests merged in 2018-11, with the labels that each got.

#440 Fixing hero title margin
  _config.yml
  _sass/pages/landing.scss
Labels: WIP

#547 Update wording & formatting of billing FAQs
  pricing.html
Labels: blog, improvement

#552 [NEW] Android 3.1 release post
  _posts/2018/09/android_release_2_6_0
  _posts/2018/11/2018-11-05-android-release-3-1.md
  images/posts/2018/11/2018-11-05-android-release-3-1/android-3-1-cover.jpg
Labels: blog post, new

#560 Add certain blog posts to Case Studies category
  _posts/2018/06/2018-06-5-gsoc-post-1.md
  _posts/2018/08/2018-08-01-GSoC-Post-3.md
  _posts/2018/08/2018-08-16-public-launch.md
  _posts/2018/09/2018-09-17-RC-Nextcloud-partnership-post.md
  _posts/2018/10/2018-10-19-stefanini-rc-partnership.md
  _posts/2018/10/2018-10-22-rc-gluu-partnership.md
Labels: blog, improvement

#574 Correct typos & wording on Stefanini post
  _posts/2018/10/2018-10-19-stefanini-rc-partnership.md
Labels: blog post, improvement

#575 Add new press to Blog
  _data/press.yml
  _posts/2018/11/2018-11-16-gabriel-engel-guest-OS-underdogs-podcast.md
  _posts/2018/11/2018-11-16-rocket.chat-featured-in-silicon-india-magazine.md
  _posts/2018/11/2018-11-16-silicon-india-magazine-livechat.md
  blog/index.html
  images/posts/2018/11/2018-11-05-gabriel-engel-guest-OS-underdogs-podcast/rocket-chat-gabe-engel-OSU-podcast.jpg
  images/posts/2018/11/2018-11-16-rocket.chat-featured-in-silicon-india-magazine/SI-logo.jpg
  images/posts/2018/11/2018-11-16-silicon-india-magazine-livechat/SI-LiveChat.jpg
  images/press/OS-podcast-logo.jpg
  images/press/SI-LiveChat-logo.jpg
  images/press/SI-logo.jpg
Labels: blog, improvement, new

#577 Add new Nextcloud integration doc to original announcement blog post
  _posts/2018/09/2018-09-17-RC-Nextcloud-partnership-post.md
Labels: blog post, improvement

#578 Update Team Page
  _data/team.yml
Labels: improvement

#600 Add new AWS infographic
  awsrocketchat.html
  images/aws/Desktop HD.png
Labels: improvement

#602 Update aws infographic
  awsrocketchat.html
  images/aws/rc_diagram.png
Labels: improvement

#601 AWS Marketplace announcement post
  _posts/2018/11/2018-11-28-rocket-chat-launches-on-aws-marketplace.md
  images/posts/2018/11/2018-11-28-rocket-chat-launches-on-aws-marketplace/AWS-Container-Marketplace.png
  images/posts/2018/11/2018-11-28-rocket-chat-launches-on-aws-marketplace/aws-marketplace-logo.png
  images/posts/2018/11/2018-11-28-rocket-chat-launches-on-aws-marketplace/aws-post-cover.jpg
Labels: blog post, new
