Repository RocketChat/rocketchat.github.io, pull requests merged in 2018-09, with the labels that each got.

#431 Add Atlassian banner with link to Migration post
  index.html
Labels: new

#432 Temporary: Change self-managed to support
  pricing.html
Labels: improvement

#438 Add link to HipChat importers on Welcome article
  _posts/2018/08/2018-08-7-welcome-to-rocketchat.md
Labels: blog post, improvement

#441 Add images to the Marketplace Preview post
  _posts/2018/08/2018-08-31-marketplace-vision-post.md
  images/posts/2018/08/marketplace-post/Marketplace-Admin.png
  images/posts/2018/08/marketplace-post/app-example-dropbox.png
  images/posts/2018/08/marketplace-post/app-example-jitsi.png
Labels: blog post, improvement

#439 0.69 release post
  _posts/2018/07/2018-07-17-v66-release-post.md
  _posts/2018/09/2018-09-07-0-69-release.md
  images/posts/2018/09/2018-09-07-0-69-release/69-cover.jpg
  images/posts/2018/09/2018-09-07-0-69-release/BBB-Mconf-integration.png
  images/posts/2018/09/2018-09-07-0-69-release/Marketplace-Admin.png
  images/posts/2018/09/2018-09-07-0-69-release/PAT-account-view.png
  images/posts/2018/09/2018-09-07-0-69-release/PAT-success.png
  images/posts/2018/09/2018-09-07-0-69-release/after-logo-centered.png
  images/posts/2018/09/2018-09-07-0-69-release/after-message-attachment-bug-fixed.png
  images/posts/2018/09/2018-09-07-0-69-release/app-example-jitsi.png
  images/posts/2018/09/2018-09-07-0-69-release/before-logo-centered.png
  images/posts/2018/09/2018-09-07-0-69-release/before-message-attachment-bug-fixed.png
  images/posts/2018/09/2018-09-07-0-69-release/buttons.gif
  images/posts/2018/09/2018-09-07-0-69-release/enable-PA-tokens-admin.png
  images/posts/2018/09/2018-09-07-0-69-release/role-tag-lighter.png
  images/posts/2018/09/2018-09-07-0-69-release/unread-items-bolder.png
Labels: blog post, new

#442 Update links on historic release posts to reflect new /install page
  _posts/2017/08/2017-08-26-new-desktop-app-release-available-for-windows-linux-and-macos.md
  _posts/2017/12/2017-12-27-rocket-chat-0-60-released.md
  _posts/2018/01/2018-01-05-hyperledger-chooses-rocket-chat.md
  _posts/2018/01/2018-25-01-desktop-apps-hotfix.md
  _posts/2018/04/2018-04-11-rocket-chat-0-63-released.md
  _posts/2018/05/2018-05-30-0-65-0-release.md
  _posts/2018/07/2018-07-17-v66-release-post.md
Labels: blog, improvement

#444 Add Drupal Europe panel to Events page
  _posts/2018/09/2018-09-10-drupal-europe.md
Labels: Events, new

#445 Add link to marketplace now it's live
  _posts/2018/08/2018-08-31-marketplace-vision-post.md
Labels: blog post, improvement

#426 Adding a message when there is no apps on a list
  _sass/pages/landing.scss
  marketplace.html
  marketplace.js
Labels: improvement

#424 Android 2.6 release post
  _posts/2018/09/2018-09-12-android_release_2_6_0.md
  _posts/2018/09/android_release_2_6_0
  images/posts/2018/09/2018-09-12-android_release_2_6_0/android-2-6-cover.jpg
Labels: blog post, new

#472 [WIP] More pricing pages fixes
  _config.yml
  _includes/pricing-table.html
  _sass/components/pricing-table.scss
  _sass/pages/pricing.scss
  _sass/ui/buttons.scss
  pricing.html
Labels: WIP
