Repository RocketChat/rocketchat.github.io, pull requests merged in 2018-10, with the labels that each got.

#492 Update LiveChat section on homepage
  index.html
Labels: improvement

#496 Update Mconf logo on Partners page
  _data/partners.yml
  images/partners/logos/brave.png
  images/partners/logos/chef.png
  images/partners/logos/consulthap.png
  images/partners/logos/containership.png
  images/partners/logos/curvestone.png
  images/partners/logos/gcp.png
  images/partners/logos/keycdn.png
  images/partners/logos/layershift.png
  images/partners/logos/mconf.png
  images/partners/logos/netways.png
  images/partners/logos/openenvy.png
  images/partners/logos/rackspace.png
  images/partners/logos/rocketchatlaucher.png
  images/partners/logos/rtm.png
  images/partners/logos/sourceforte.png
  images/partners/logos/spinups.png
  images/partners/logos/tokenly.png
  images/partners/logos/vortigo.png
  images/partners/logos/zenvia.png
  images/partners/logos/zibtek.png
  images/partners/mconf-updated.png
  images/partners/mconf.png
Labels: improvement

#454 Update Press page with latest articles
  _data/press.yml
  images/press/B2C-logo.jpg
  images/press/Black-Duck-Logo.jpg
  images/press/VentureBeat-Logo.jpg
  images/press/blockchain-news-logo.jpg
  images/press/cape-town-uni-logo.jpg
  images/press/pl-logo.jpg
  images/press/softex-logo.jpg
  images/press/theregisterlogo.jpg
  images/press/timecamp-logo.jpg
Labels: WIP, improvement

#505 Add event & cover photo to Events - Gartner
  _posts/2018/10/2018-10-12-gartner-symposium-itxpo.md
  images/posts/2018/10/2018-10-12-gartner-symposium-itxpo/gartner-symposium-itxpo-orlando.jpg
Labels: Events, new

#508 Update Features section on Homepage
  index.html
Labels: improvement

#511 Update London address
  contact.html
Labels: improvement

#515 Replace banner link to blog post with link to Atlassian page
  index.html
Labels: improvement

#516 Add link to Atlassian page on homepage
  index.html
Labels: improvement

#517 Add link to Atlassian page to blog post + add new cover photo
  _posts/2018/08/2018-08-7-welcome-to-rocketchat.md
  images/posts/2018/08/2018-08-7-welcome-to-rocketchat/hipchat-rc-cover.jpg
Labels: blog post, improvement

#520 Fix HipChat blog post cover
  _posts/2018/08/2018-08-7-welcome-to-rocketchat.md
Labels: blog post, improvement

#522 Add All Things Open to Events
  _posts/2018/10/2018-10-19-all-things-open.md
  images/posts/2018/10/2018-10-19-all-things-open/ATL-logo.png
Labels: Events, new

#521 Stefanini x RC partnership post
  _posts/2018/09/2018-09-17-RC-Nextcloud-partnership-post.md
  _posts/2018/10/2018-10-19-stefanini-rc-partnership.md
  images/posts/2018/10/2018-10-19-stefanini-rc-partnershi/stefanini-rc-cover.png
Labels: WIP, blog post

#525 RC support for OSI
  _posts/2018/10/2018-10-22-rc-joins-OSI.md
Labels: blog post, new

#531 Update Nextcloud partnership post
  _posts/2018/09/2018-09-17-RC-Nextcloud-partnership-post.md
  images/posts/2018/09/2018-09-17-RC-Nextcloud-partnership-post/integration-demo.gif
  images/posts/2018/09/2018-09-17-RC-Nextcloud-partnership-post/rocket.chat-integration.gif
Labels: blog post, improvement

#532 Add Oracle OpenWorld 2018 to Events
  _posts/2018/10/2018-10-23-oracle-open-world.md
  images/posts/2018/10/2018-10-23-oracle-open-world/ORACLE-openworld-rocketchat.jpg
Labels: Events, new

#523 Rocket.Chat x Gluu partnership post
  _posts/2018/10/2018-10-22-rc-gluu-partnership.md
  images/posts/2018/10/2018-10-22-rc-gluu-partnershi/gluu-rc-team-photo-cover.jpg
Labels: blog post, new

#534 Change date to today for Gluu post
  _posts/2018/10/2018-10-22-rc-gluu-partnership.md
Labels: blog, improvement

#535 Fix typo in Gluu post
  _posts/2018/10/2018-10-22-rc-gluu-partnership.md
Labels: blog, improvement

#538 [FIX] Add parallax effect back to pricing page
  _config.yml
  main.js
Labels: improvement
